### ISSUE TITLE
Readme.md modify

### ISSUE THREAD

**Issue by sarthakahuja11** [CAT-Technologies/GrocerEase#110]
Readme.md modify - decide what to keep in the end - after wiki completed - either hyperlink to wiki or just keep main things/installation framework there.

UT section, future plans, doxygen link to be added in wiki @AzvenusK - also post the wiki contents you noted here please for reference

Build_test badge can be added n even the pretty fetch open thing you showed @addy1997 

One final 2-2.5 min video from me n @jwtan5  also goes potentially on readme home

**Comment by addy1997** [comment]
> Readme.md modify - decide what to keep in the end - after wiki completed - either hyperlink to wiki or just keep main things/installation framework there.
> 
> UT section to be added in wiki @AzvenusK
> 
> Build_test badge can be added n even the pretty fetch open thing you showed @addy1997
> 
> One final 2-2.5 min video from me n @jwtan5 also goes potentially on readme home

Batches added. Will try to add the codefetch if it gives proper stats in wiki. Is it okay?

**Comment by sarthakahuja11** [comment]
> > Readme.md modify - decide what to keep in the end - after wiki completed - either hyperlink to wiki or just keep main things/installation framework there.
> > UT section to be added in wiki @AzvenusK
> > Build_test badge can be added n even the pretty fetch open thing you showed @addy1997
> > One final 2-2.5 min video from me n @jwtan5 also goes potentially on readme home
> 
> Batches added. Will try to add the codefetch if it gives proper stats in wiki. Is it okay?

Thanks, yes you can add it in wiki/repo as you wish

**Comment by addy1997** [comment]
I think we have added almost everything to the readme. If so, can I close this issue? @sarthakahuja11

**Comment by sarthakahuja11** [comment]
@addy1997 one hyper link inside readme to our wiki and that should be it I think!

**Comment by sarthakahuja11** [comment]
codefetch we will not do right?

**Comment by addy1997** [comment]
No. Closing this.

**Comment by addy1997** [comment]
Okay
