### ISSUE TITLE
Integrate GPIO code seamlessly with BLE logic

### ISSUE THREAD

**Issue by sarthakahuja11** [CAT-Technologies/GrocerEase#20]
Can be edited, just for reference

**Comment by addy1997** [comment]
> Can be edited, just for reference

Could you elaborate?

**Comment by sarthakahuja11** [comment]
As in this issue description/title is very generic. Can be changed as per technical terms when approaching it.

**Comment by addy1997** [comment]
> As in this issue description/title is very generic. Can be changed as per technical terms when approaching it.

alright! I will do that.

**Comment by sarthakahuja11** [comment]
Fix Rssi David code 
Mobile app - app to the beacon (laptop)
David code - cart to beacon & cart (raspi) to phone
One more - app send Rssi to transmit to cart 
Once we have all 3, run them to separate threads - use piping - transmit data from different threads - use together, refer david's code for using together

Conclusions - convert RSSI (dB) to perform subsequent calculations

**Comment by sarthakahuja11** [comment]
Links to be added here @sarthakahuja11

**Comment by sarthakahuja11** [comment]
Raspi

- [ ]  Get RSSI from phone 

- [ ]  Get RSSI from beacon (laptop)

- [ ]  Get RSSI from phone (phone to beacon)

- [x]  Use these 3 distances, and formula to compute distance

- [ ]  Run three of them in separate threads - use piping - transmit data from different threads (if possible ?)

- [ ]  Calculate Maneuver accordingly

- [x] Actuate as per needed

Add more links:

https://forums.raspberrypi.com/viewtopic.php?t=146273

**Comment by sarthakahuja11** [comment]
On going, final testing  going, to be merged soon
