### ISSUE TITLE
feasibility of implementing controller for robot movement

### ISSUE THREAD

**Issue by jwtan5** [CAT-Technologies/GrocerEase#33]
Fuzzy logic controller, Neural network controller, PID, etc.

**Comment by addy1997** [comment]
*Block diagram for fuzzy logic controller*
![image](https://user-images.githubusercontent.com/29406906/155952053-b310811f-c9cf-471e-9298-874f2e50080e.png)

*Block diagram 1 for neural network controller*
![image](https://user-images.githubusercontent.com/29406906/155952341-4f04655d-1400-4680-8c27-348fb000effd.png)

*Block diagram 2 for neural network controller*
![image](https://user-images.githubusercontent.com/29406906/155952420-b5110ee4-b4f4-44a1-9ffc-6f4cc34fe5ad.png)

In this block diagram the *angle of the arm* can be replaced by the *turning angle of the cart* which we calculated [here](https://github.com/CAT-Technologies/GrocerEase/blob/compute_angle/Compute_Angle/compute_angle.cpp)

@jwtan5, I am working on this. What do you think?

**Comment by sarthakahuja11** [comment]
https://github.com/Lavr18/MR-Obstacle-Avoidance
Suggested  by Adwait, look into it or other options

**Comment by sarthakahuja11** [comment]
Just for documentation, 
Current approach: Fuzzy logic (Need to help David)
Futuristic approach: Neural Network

**Comment by addy1997** [comment]
@jwtan5, we are done with this, right? Can I close this issue?

**Comment by jwtan5** [comment]
yes
