### ISSUE TITLE
Added dependabot.yml file for alerts

### ISSUE THREAD

**Issue by addy1997** [CAT-Technologies/GrocerEase#60]
@sarthakahuja11, I had to change the *.github_Template* folder of yours into a *.github* folder. In turn, this change introduced a dedicated template for creating bug reports and feature requests. Unbeknownst to you, I changed it in the morning. It hasn't altered anything in the repository so far.
Sorry!

**Comment by sarthakahuja11** [comment]
changing anything is fine in repo you don't need permission..


If you change something, make sure you mention 1. Reason, 2. Impact of changes if any.

Let me know about both, it's fine

**Comment by addy1997** [comment]
> changing anything is fine in repo you don't need permission..
> 
> If you change something, make sure you mention 1. Reason, 2. Impact of changes if any.
> 
> Let me know about both, it's fine

@sarthakahuja11, this is what it basically does. Check PR #74. Hope this clears any confusion.

**Comment by sarthakahuja11** [comment]
@addy1997 Ohh I understand the effects of this template when i create a new issue...We should keep it or not?

**Comment by addy1997** [comment]
We should
