### ISSUE TITLE
error: taking address of temporary [-fpermissive]

### ISSUE THREAD

**Issue by addy1997** [CAT-Technologies/GrocerEase#64]
**Describe the bug**
This bug is due to incorrect declaration of the variable type which is latter called in bacpy()

**To Reproduce**
1. git clone https://github.com/CAT-Technologies/GrocerEase
2. cd GrocerEase
3. git pull origin rssi-calc-raspi
4. cd Raspi_RSSI
5. mkdir build && cd buid
6. cmake .. && make

**Expected behavior**
File compilation

**Screenshots**

![1](https://user-images.githubusercontent.com/29406906/159863135-306acba4-7aa2-4ad6-b582-42dea87b9542.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Mozilla

**Comment by addy1997** [comment]
Sol:

declare a constant pointer
 `const bdaddr_t *bdaddr;`

replace it with BDADDR_ANY in the bacpy function below
`bacpy(&sockAddr.l2_bdaddr, bdaddr);`

![image](https://user-images.githubusercontent.com/29406906/159864552-835d527c-22b5-494b-876c-7d8d3dd0c59a.png)

**Comment by sarthakahuja11** [comment]
Make is fine, thanks @addy1997.

But did you execute/run the code after that?

It gives segmentation fault - core dumped just when I run it with this approach

**Comment by addy1997** [comment]
@sarthakahuja11, I am closing this.
