### ISSUE TITLE
Hardware setup and integrations needed

### ISSUE THREAD

**Issue by sarthakahuja11** [CAT-Technologies/GrocerEase#7]

**Comment by jwtan5** [comment]
**I/O -> L298N**
5 - IN1 (OUT)
6 - IN2 (OUT)
13 - ENA_A (ANALOG_OUT)
23 - IN3 (OUT)
24 - IN4 (OUT)
12 - ENA_B (ANALOG_OUT)

**I/O -> IR**
4 - IR_LEFT (IN)
14 - IR_RIGHT (IN)

_(IR_MID tbd)_

**Comment by addy1997** [comment]
on it.

**Comment by sarthakahuja11** [comment]
This is different from the GPIO code right? Just asking..

**Comment by sarthakahuja11** [comment]
> **I/O -> L298N** 5 - IN1 (OUT) 6 - IN2 (OUT) 13 - ENA_A (ANALOG_OUT) 23 - IN3 (OUT) 24 - IN4 (OUT) 12 - ENA_B (ANALOG_OUT)
> 
> **I/O -> IR** 4 - IR_LEFT (IN) 14 - IR_RIGHT (IN)
> 
> _(IR_MID tbd)_



@jwtan5 Is this 100% complete now? or any dependencies left? Just asking..
