### ISSUE TITLE
Social Media phase 2

### ISSUE THREAD

**Issue by sarthakahuja11** [CAT-Technologies/GrocerEase#87]

**Comment by addy1997** [comment]
Please, let me know if you need any help.

**Comment by sarthakahuja11** [comment]
Only 3 posts up in phase 1 (ends today)
Phase has 4-5 posts, daily one ideally - aggressive PR and then i'll tell PR strategy

**Comment by sarthakahuja11** [comment]
Phase 2 in progress going well.

Closing in on 2000 views in a short Instagram video! 

Need to add 1-2 more posts daily and start aggressive publicity now as we have enough content.

1. Trilateration concept + RSSI post 
2. BLE App/bluetooth rssi screen record post
3. David screen grab angle updation + IR testing perfection post
4. Final video 2 mins + with david n myself
5. Anything extra if needed

**Comment by addy1997** [comment]
> 

Your efforts are coming to fruition. Well done! Awesome PR.

**Comment by addy1997** [comment]
Closing this issue.
