### ISSUE TITLE
Issues with the main_program

### ISSUE THREAD

**Issue by addy1997** [CAT-Technologies/GrocerEase#99]
See the issues below.

**Comment by addy1997** [comment]
![image](https://user-images.githubusercontent.com/29406906/163526413-dfd8edb9-9611-44e5-8640-cec803c1b31d.png)

**Comment by addy1997** [comment]
**UPDATE**
![image](https://user-images.githubusercontent.com/29406906/163565662-bf12e05c-d0e1-4822-9426-16f59a16f895.png)


@sarthakahuja11, FIX THESE PLEASE.

**Comment by sarthakahuja11** [comment]
@addy1997  please check I fixed all hopefully

https://github.com/CAT-Technologies/GrocerEase/commit/bb44cabcdcaf5933d61295c36d69a2328bb6ec2f

pigpio.h still not found, please fix that ASAP

**Comment by addy1997** [comment]
@sarthakahuja11, should this issue be closed, as @jwtan5 has changed the files with (#106)?

**Comment by sarthakahuja11** [comment]
Yes
